# Generated by Django 4.0.2 on 2022-02-26 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('keyword', models.CharField(max_length=120)),
                ('result', models.CharField(max_length=500)),
                ('searched_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
